title: PloxHost Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.plox.host'
params:
  alwaysKeepBrandColor: true
  brand: '#158f8a'
  categories:
    - closed: true
      description: The main servers are located here.
      name: North Coast
    - name: East Coast
    - name: Uncategorized
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disableDarkMode: false
  disrupted: '#cc4400'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: 'https://plox.host/assets/img/plox-logo-long.png'
  notice: '#24478f'
  ok: '#008000'
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - category: North Coast
      name: Gateway
    - category: East Coast
      name: Backup Gateway
    - category: Uncategorized
      description: The guts of the application.
      name: API
    - category: Uncategorized
      description: >-
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      name: Media Proxy
  useLargeHeaderDesign: true
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
